import nodemailer from 'nodemailer';
import { NextResponse } from 'next/server';


const transporter = nodemailer.createTransport({
    port: 465,
    host: "smtp.gmail.com",
    auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASSWORD, // App password generated by google
    },
    secure: true,
})

export async function POST(req: Request)
{
    const body = await req.json();
    const { name, email, message } = body;

    // Validate email format
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))
    {
        console.error('Invalid email format');
        return new NextResponse('Invalid email format', { status: 400 });
    }

    const mailOptions = {
        from: process.env.EMAIL_USER, // Replace with your email address
        to: [email, process.env.EMAIL_USER], // Send to user and yourself
        subject: 'New message from your portfolio website',
        html: `
        <h3>New message from ${name}</h3>
        <p>${message}</p>
      `,
    };

    try
    {
        await transporter.sendMail(mailOptions);
        return new NextResponse('Email sent successfully', { status: 200 });
    } catch (error)
    {
        console.error(error);
        return new NextResponse('Failed to send email', { status: 500 });
    }
}
